### ISSUE TITLE
Failed to activate the collaboratom package

### ISSUE THREAD

**Issue by Qzen** [HACKxFDU/collaboratom#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [collaboratom](https://github.com/HACKxFDU/collaboratom) package 0.2.1

### Stack Trace

Failed to activate the collaboratom package

```
At Cannot read property 'onDidChangeSelectionRange' of undefined

TypeError: Cannot read property 'onDidChangeSelectionRange' of undefined
    at Object.activate (/packages/collaboratom/lib/collaboratom.js:58:34)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:00.1.0 core:confirm (input.hidden-input)
     -0:18.1.0 collaboratom:connection (div.panels-item)
  2x -0:08.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-arma-language 0.3.0 
atom-clock 0.1.7 
atom-material-syntax 1.0.6 
atom-material-ui 1.3.10 
collaboratom 0.2.1 
language-arma-atom 2.9.0 
language-sqf 0.3.0 
```

**Comment by dragonly** [comment]
thanks for using this atom plugin, but unfortunately this plugin is not long-time maintained. maybe i will return and put some effort on that in the coming months. PR is welcomed :D
